/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125509-g8ad6288553-20260709"
#endif /* AVUTIL_FFVERSION_H */
